name: Mac CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        brew update
        brew install tcl-tk@8 autoconf curl
        brew reinstall tcl-tk@8
        find /usr -name tclConfig.sh
        find /opt -name tclConfig.sh
    - name: configure
      run: |       
        autoreconf -vi
        ./configure --with-tcl=/opt/homebrew/opt/tcl-tk/lib --prefix=/usr/local        
    - name: make
      run: make
    - name: install
      run: sudo make install
    - name: test
      run: make test
